### ISSUE TITLE
UCD seems to always create the user 'clear'

### ISSUE THREAD

**Issue by markdryan** [clearlinux/micro-config-drive#28]
When provisioning a new Clearlinux cloud image with UCD a new user called clear seems to get created automatically and assigned the default uid of 1000.  Is this user really needed?  Should it be left around after UCD has finished?  Assuming it is needed, would it be possible to create it with a UID and GID other than 1000?  This would allow the first user create user to have these default credentials.

**Comment by donnydavis** [comment]
This is pretty standard practice for cloud images. Most of the other distros do the same thing.

https://docs.openstack.org/image-guide/obtain-images.html

**Comment by ahkok** [comment]
It's configurable, both through a compile time option, and through use of the cloud-init file.
