### ISSUE TITLE
ucd should be the last service to start

### ISSUE THREAD

**Issue by donnydavis** [clearlinux/micro-config-drive#40]
The ucd service starts too early and can cause a race condition. Moving the service to start after multi-user.target resolves the issue

**Comment by donnydavis** [comment]
Here is one that actually works. forgot to add in RequiredBy

https://github.com/clearlinux/micro-config-drive/pull/42

**Comment by ahkok** [comment]
This is obsolete, and, in closing this we established that no unit ordering should be required for `ucd` to function - it must be able to handle the (un)availability of network, for instance.
