### ISSUE TITLE
Simple Feature Request: Retrieve & Set Hostname

### ISSUE THREAD

**Issue by armenr** [clearlinux/micro-config-drive#57]
As per this thread: https://community.clearlinux.org/t/how-to-retrieve-instance-hostname-from-ucd/8096

## Context
I know that ucd generates /var/lib/cloud/aws-user-data when the ucd systemd oneshot runs.

What I want to understand is whether ucd also fetches the instance hostname from metadata → the same output that you’d get from curl --silent http://169.254.169.254/latest/meta-data/hostname on an EC2.

The reason I ask is because putting `curl --silent http://169.254.169.254/latest/meta-data/hostname > /opt/hostname.txt` into a systemd oneshot appears to take about 5 seconds to run, and ucd is significantly faster (and has already done the work of interacting with the metadata API).

Even a 5 second boot delay here has a practical/measurable impact on our infrastructure use-case...although I know I might be sounding greedy or a bit too "optimize-all-the-things!"

## The Feature
Enable UCD to set a cloud instance's default hostname based on the user metadata API (`hostnamectl` + `/etc/hosts/`).

^^ IF the above is too opinionated or controversial, could we at least get the hostname dropped off/saved somewhere in `/var/lib/cloud/` ?

Thank you!! :)

**Comment by ahkok** [comment]
@bwarden and me discussed this and it wouldn't be too difficult to add*:
- We can extend the `ucd-data-fetch` to do an additional `http` request to fetch the hostname file if it is known that the data provider supports this (i.e. it has to be a simple file with just the name in it, on a separate simple URL on the server)
- It can then expand the written out `user-data` file to add this name.

**Comment by ahkok** [comment]
> I'm curious...With |ucd| or |ucd-data-fetch| --> How were you able to 
get that time down to ~1 second?



Message ID: ***@***.***>

`ucd-data-fetch` fetches with HTTP only, and directly connects to a 
hard-coded IP address, so there is no hostname lookup, TLS/SSL or DNS 
required. This can save a ton of time on a freshly booted system, as all 
those caches are empty right after boot.

**Comment by bwarden** [comment]
> Does the http client implementation also take IMDS v2 into consideration?

No, the client fetcher only does simple GET requests -- no tokens.

**Comment by bwarden** [comment]
Do you actually get a value from `curl --silent http://169.254.169.254/latest/meta-data/hostname`? If the fetcher doesn't get anything, it won't write the `hostname:` tag. If it does, it will write it immediately following the SSH keys and prior to the user data.

**Comment by bwarden** [comment]
> but I think that might be a separate Github Issue...

Yes, please open a new issue for that. Include a redacted copy of your aws-cloud-data file if you can.
