### ISSUE TITLE
New hostname feature breaks user-data

### ISSUE THREAD

**Issue by Timbus** [clearlinux/micro-config-drive#59]
The change made in commit bd96e691a4d4 writes the hostname to the constructed cloud-init config. That's cool but unfortunately it doesn't appear to write a newline after the host value.
This means due to the strange composition behavior documented in issue #54, userdata is now being appended to the hostname and is not running correctly.

My workaround has been to tweak our userdata to contain newlines at the start. It feels a bit hacky

**Comment by bwarden** [comment]
Watch for https://github.com/clearlinux-pkgs/micro-config-drive/releases/tag/48-35
